# =======================================
# Global Configuration
# =======================================
spring:
  application:
    name: hop-huddles-api

  profiles:
    active: development

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        # ⚠️ Use the correct dialect in production
        dialect: org.hibernate.dialect.H2Dialect
        #       dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.hqc.hophuddles: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# =======================================
# Development Profile
# =======================================
---
spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# =======================================
# Production Profile (Azure SQL)
# =======================================
---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:sqlserver://${AZURE_SQL_SERVER}.database.windows.net:1433;database=${AZURE_SQL_DATABASE};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${AZURE_SQL_USERNAME}
    password: ${AZURE_SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# =======================================
# Auth0 Configuration (Common)
# =======================================
auth0:
  domain: ${AUTH0_DOMAIN:dev-2bcqxbprxonz42ic.us.auth0.com}
  audience: ${AUTH0_AUDIENCE:https://hop-huddles-api}
  client-id: ${AUTH0_CLIENT_ID:9fZ7aOnG98gErQumOTbU57wEkYMW8jzq}
  client-secret: ${AUTH0_CLIENT_SECRET:A7XfvFoiEkc0ltX2CenSVZPF7Wwo3NbELJRVc_1Gr_9dNS9qoAMNg09eJeXpoj6o}
  management-api-audience: ${AUTH0_MGMT_API_AUDIENCE:https://dev-2bcqxbprxonz42ic.us.auth0.com/api/v2/}
  management-api-client-id: ${AUTH0_MGMT_CLIENT_ID:ZBIp5Qnb7jUvkEUfF0pa3fgLScxMEmT2}
  management-api-client-secret: ${AUTH0_MGMT_CLIENT_SECRET:814mVbt_zqWrGjEfRtnnbS6dU-QREUPITWQA-L1WqYGqtQ6lpiLVWTJc5qc1j1Zq}

# =======================================
# Shared Configuration (All Profiles)
# =======================================
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/

app:
  auth:
    enabled: false
    jwt:
      secret: mySecretKey12345678901234567890123456789012345678901234567890
      expiration: 86400000

  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"

  file:
    upload-dir: uploads/
    max-size: 10485760

---
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  cache:
    type: simple

logging:
  level:
    com.hqc.hophuddles: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
