# src/main/resources/application.yml
spring:
  application:
    name: hop-huddles-api

  profiles:
    active: development

  # JPA Configuration for Performance
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        # Remember to change this H2Dialect to ServerDialect when production **********************************
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: false
        use_sql_comments: false
        # Performance optimizations
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        # Connection pool settings
        connection:
          provider_disables_autocommit: true
        # Query cache
        cache:
          use_second_level_cache: false
          use_query_cache: false

  # Connection pool for thousands of users
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1
  compression:
    enabled: true
  http2:
    enabled: true

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Logging
logging:
  level:
    com.hqc.hophuddles: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

---
# Development Profile
spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#---
## Development Profile
#spring:
#  config:
#    activate:
#      on-profile: development
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/hop_huddles_dev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 8298
#
#  jpa:
#    hibernate:
#      ddl-auto: create  # Or use 'update' if you want to keep data
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect


---
# Production Profile (Azure SQL)
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:sqlserver://${AZURE_SQL_SERVER}.database.windows.net:1433;database=${AZURE_SQL_DATABASE};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${AZURE_SQL_USERNAME}
    password: ${AZURE_SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# Performance monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,env
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

spring.jackson:
  serialization:
    indent-output: true
    write-dates-as-timestamps: false
  deserialization:
    fail-on-unknown-properties: false
  default-property-inclusion: non_null

# Add for better error handling
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false