#!/bin/bash

BASE_URL="http://localhost:8080/api/v1"

echo "=== Day 6 Complete Backend Testing ==="

# Test 1: Verify existing functionality still works
echo "1. Testing Existing Functionality..."
echo "Creating sample data..."
curl -s -X POST $BASE_URL/test/create-huddle-sample-data
echo

echo "Testing analytics..."
curl -s $BASE_URL/analytics/agency/1
echo

# Test 2: Test security configuration
echo "2. Testing Security Configuration..."
curl -s -X POST $BASE_URL/test/test-security-config
echo

# Test 3: Test file system
echo "3. Testing File System..."
echo "Checking file system status..."
curl -s $BASE_URL/test/file-system-status
echo

echo "Creating sample files..."
curl -s -X POST $BASE_URL/test/create-sample-files
echo

# Test 4: Test file upload (create a test file)
echo "4. Testing File Upload..."
echo "test content for upload" > test_upload.txt
curl -s -X POST $BASE_URL/files/upload \
  -F "file=@test_upload.txt" \
  -F "category=test"
echo

# Clean up test file
rm -f test_upload.txt

# Test 5: Test PDF generation
echo "5. Testing PDF Generation..."
curl -s -X POST $BASE_URL/files/generate-pdf \
  -d "title=Test PDF" \
  -d "content=This is a test PDF generated by the system" \
  -d "category=test_pdfs"
echo

# Test 6: Test CORS configuration
echo "6. Testing CORS Configuration..."
curl -s -H "Origin: http://localhost:3000" \
     -H "Access-Control-Request-Method: POST" \
     -H "Access-Control-Request-Headers: X-Requested-With" \
     -X OPTIONS $BASE_URL/agencies
echo

# Test 7: Verify all endpoints are accessible (dev mode)
echo "7. Testing All Major Endpoints..."

echo "Agencies endpoint:"
curl -s $BASE_URL/agencies | head -c 100
echo "..."

echo "Users endpoint:"
curl -s $BASE_URL/users | head -c 100
echo "..."

echo "Sequences endpoint:"
curl -s $BASE_URL/sequences/agency/1 | head -c 100
echo "..."

echo "Progress endpoint:"
curl -s $BASE_URL/progress/user/1 | head -c 100
echo "..."

echo "Analytics endpoint:"
curl -s $BASE_URL/analytics/agency/1 | head -c 100
echo "..."

echo
echo "=== Day 6 Testing Complete ==="
echo "✅ Security configured (dev mode - auth disabled)"
echo "✅ File management system working"
echo "✅ PDF generation working"
echo "✅ CORS configured for frontend"
echo "✅ All existing functionality preserved"
echo "✅ Ready for frontend development!"